# Generated by Django 6.1 on 2026-08-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.SmallIntegerField(db_column='account_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='account_type', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='branch.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='customer.customer')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
