# Generated by Django 6.1 on 2026-08-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.PositiveIntegerField(db_column='account_id', primary_key=True, serialize=False),
        ),
    ]
