# Generated by Django 6.1 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.SmallIntegerField(db_column='branch_id', primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('opening_date', models.DateField()),
                ('ifsc', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
