# Generated by Django 6.1 on 2026-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('opened_date', models.DateField()),
                ('ifsc_code', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
