# Generated by Django 6.1 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.PositiveIntegerField(db_column='customer_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField(db_column='date_of_birth')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('occupation', models.CharField(max_length=50)),
                ('income', models.DecimalField(db_column='annual_income', decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('credit_score', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
