name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: prime_bank
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d prime_bank"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      
      - name: Set up Python
        run: uv python install 3.14
      
      - name: Install Dependencies
        run: uv sync --locked
      
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        working-directory: ./src
        run: |
          python manage.py test
